spring.profiles.active: develop
server:
  port: 9090
tweet-properties:
  followers-min:
    1500
  allowed-languages:
    - es
    - fr
    - it
  ranking-size:
    10

---
spring:
  profiles: develop
  jpa:
    show_sql: false
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    username: nick
    password: nick
    url: jdbc:h2:file:./h2/bddevelop
---
spring:
  profiles: test
  jpa:
    show_sql: false
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    username: nick
    password: nick
    url: jdbc:h2:file:./h2/bdtest
